### PR TITLE
v0.6.5

### PR DESCRIPTION
**Pull request by ajslater**
## v0.6.5

- Build Docker images for amd64 & arm64
- Dark admin pages

### CODE REVIEW

**Comment by jwm-evans** [comment]
There is no arm image on docker hub. Is it being hosted elsewhere?

**Comment by ajslater** [comment]
It looks like there is. I believe I'm building and pushing both images under the same tag, however I do not have an ARM machine to test with.
Screen Shot 2021-01-28 at 4 22 04 PM
https://hub.docker.com/r/ajslater/codex/tags?page=1&ordering=last_updated

**Comment by jwm-evans** [comment]
My fault. I thought Raspberry Pi OS was 64 bit. When I try a pull, this is what I get:

```
pi@comicserver:~ $ docker pull ajslater/codex:latest
latest: Pulling from ajslater/codex
no matching manifest for linux/arm/v7 in the manifest list entries
```

I'll look at re-installing with Ubuntu instead

**Comment by jwm-evans** [comment]
Works well on a Raspberry Pi 3 running Ubuntu 20.04 64bit
I'm importing my collection right now :-)

**Comment by ajslater** [comment]
Ah yes. I intentionally didn't build for ARM32 because cross-compiling is unbearably slow, and i was targeting Apple Silicon more than anything else.

**Pull request merged**
